# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main function for the MCMC loop
#'
#' @name mcmc
#'
#' @param nIter Number of MCMC iterations
#' @param burnin Length of MCMC burn-in period
#' @param thin Number of thinning
#' @param n Number of samples to draw
#' @param nsamp How many samples to draw for generating each sample; only the last draw will be kept
#' @param ninit Number of initials as meshgrid values for envelop search
#' @param metropolis TBA
#' @param simple TBA
#' @param convex Adjustment for convexity (non-negative value, default 1.0)
#' @param npoint Maximum number of envelope points
#' @param dirichlet Not yet implemented
#' @param proportion_model TBA
#' @param BVS TBA
#' @param gamma_prior TBA
#' @param gamma_sampler TBA
#' @param eta_prior TBA
#' @param eta_sampler TBA
#' @param initList TBA
#' @param rangeList TBA
#' @param hyperparList TBA
#' @param datEvent TBA
#' @param datTime TBA
#' @param datX TBA
#' @param datX0 TBA
#' @param datProportionConst TBA
#'
run_mcmc <- function(nIter, burnin, thin, n, nsamp, ninit, metropolis, simple, convex, npoint, dirichlet, proportion_model, BVS, gamma_prior, gamma_sampler, eta_prior, eta_sampler, initList, rangeList, hyperparList, datEvent, datTime, datX, datX0, datProportionConst) {
    .Call(`_GPTCM_run_mcmc`, nIter, burnin, thin, n, nsamp, ninit, metropolis, simple, convex, npoint, dirichlet, proportion_model, BVS, gamma_prior, gamma_sampler, eta_prior, eta_sampler, initList, rangeList, hyperparList, datEvent, datTime, datX, datX0, datProportionConst)
}

